### ISSUE TITLE
Can't get this running locally

### ISSUE THREAD

**Issue by lizzzp1** [jscomplete/bakesale#7]
Not sure if I'm missing something.
Logged the actual error and it looks like it's from a dependency? 

![screen shot 2017-10-01 at 5 51 35 pm](https://user-images.githubusercontent.com/7826059/31059514-773750c2-a6d1-11e7-9332-0f5f8c44aac2.png)

**Comment by lizzzp1** [comment]
Will be happy to contribute to the README once I figure it out 😄

**Comment by samerbuna** [comment]
@lizzzp1 the setup process is a bit complicated, the project depends on a GraphQL schema. 

I want to make it easier to create a dev schema but that requires some effort. There is a test schema you can use but you'll probably have more questions. 

Are you on [jsComplete's Slack](https://slackin-bfcnswvsih.now.sh/)?

**Comment by lizzzp1** [comment]
I am now!
